- name: Configure Ubuntu EC2 Instance
  hosts: all
  become: true  # Run as sudo
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - curl
          - git
          - unzip
          - python3-pip
          - python3-venv
        state: present

    - name: Install Node.js and npm
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    - name: Verify Node.js and npm installation
      command: node -v
      register: node_version
      changed_when: false

    - debug:
        msg: "Node.js version: {{ node_version.stdout }}"

    - name: Install PM2 globally
      npm:
        name: pm2
        global: yes

    - name: Save PM2 process list
      command: pm2 save

    - name: Configure PM2 to start on reboot
      command: pm2 startup systemd
